### ISSUE TITLE
Cannot install into VS 2019

### ISSUE THREAD

**Issue by LeoJHarris** [renestein/ConfigureAwaitEnforcer#1]
Hi @renestein am trying to install your plugin extension into VS 2019 but getting: the following references must be present before installation can continue:

Visual Studio MPF 15.0.

I think Visual studio uses latest Visual Studio MPF 16.0

**Comment by renestein** [comment]
Hi @LeoJHarris, thanks for the reporting.
I think that Visual Studio MPF 15.0. dependency is redundant and I will fix this ASAP.

**Comment by renestein** [comment]
@LeoJHarris
 I have deleted the MPF 15.0. dependency.
Version 1.1.2. is available in the [market place](https://marketplace.visualstudio.com/items?itemName=Rene-Stein.ConfigureAwaitEnforcer).

Please give it a try and let me know the result.

**Comment by LeoJHarris** [comment]
That did fix the issue thanks
