### ISSUE TITLE
Extension changes colouring scheme in editor

### ISSUE THREAD

**Issue by Toudahl** [renestein/ConfigureAwaitEnforcer#3]
I installed the extension and it changed the colouring scheme of my IDE.
Now i have Black paranthesis, curly brackets, equal signs etc, Uninstalling the extension did not change it back.

Im using VS2019 enterprise.

**Comment by renestein** [comment]
Hi @Toudahl,
thanks for the reporting. I think that reported issue is not related to this extension. The code in this extension does not change the coloring scheme.  The extension does not have a single line of the code that uses something even remotely related to the colors of the IDE.

I am using black scheme in the Visual Studio and after installing the extension my coloring scheme is untouched.

**Comment by renestein** [comment]
Closing. Feel free to reopen the issue if you have repro.

**Comment by Toudahl** [comment]
@renestein This is so strange.
I opened VS2019, installed the extension, and restarted VS as per the instructions in the extension manager. When i opened VS back up again, the colours were changed.
So only logical conclusion was the it was the extension.

I just tried to reproduce it while recording a video, and nothing happend. It works as intended.
Sorry for the inconvenience.

**Comment by renestein** [comment]
@Toudahl. Thanks for letting me know. Yes, it's something strange between VS 2019 and heaven. :)
